name: stareet
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.7
  firebase_storage: ^11.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/background.jpeg
    - assets/images/profileImage.png
    - assets/images/backgroundImage.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/textlogo.png
    - assets/images/cameralogo.png
    - assets/images/byeori.gif
    - assets/images/byeori2.gif
    - assets/images/byeori3.gif

  fonts:
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: Pretendard-ExtraLight
      fonts:
        - asset: assets/fonts/Pretendard-ExtraLight.otf
